import { Keys, MouseButtons, GamepadButtons, GamepadAxis } from './types';

// this is based on a standard Xbox 360 controller plugged into a PC.
// I guess ideally there would be a way to make different versions of
// these for different controllers and joysticks. Later improvement?
export const buttonNameLookup: Record<number, GamepadButtons> = {
	0: GamepadButtons.A,
	1: GamepadButtons.B,
	2: GamepadButtons.X,
	3: GamepadButtons.Y,
	4: GamepadButtons.L1,
	5: GamepadButtons.R1,
	8: GamepadButtons.Back,
	9: GamepadButtons.Start,
	10: GamepadButtons.LS,
	11: GamepadButtons.RS,
	12: GamepadButtons.DPadUp,
	13: GamepadButtons.DPadDown,
	14: GamepadButtons.DPadLeft,
	15: GamepadButtons.DPadRight
};

export const buttonsAsAxisLookup: Record<number, GamepadAxis> = {
	6: GamepadAxis.L2,
	7: GamepadAxis.R2
};

export const axisNameLookup: Record<number, GamepadAxis> = {
	0: GamepadAxis.LX,
	1: GamepadAxis.LY,
	2: GamepadAxis.RX,
	3: GamepadAxis.RY
};

export const mouseButtonCodes: Record<number, MouseButtons> = {
	1: MouseButtons.Left,
	3: MouseButtons.Right,
	2: MouseButtons.Middle
};

export const keyCodes: Record<number, Keys> = {
	48: Keys.Zero,
	49: Keys.One,
	50: Keys.Two,
	51: Keys.Three,
	52: Keys.Four,
	53: Keys.Five,
	54: Keys.Six,
	55: Keys.Seven,
	56: Keys.Eight,
	57: Keys.Nine,
	8: Keys.Backspace,
	9: Keys.Tab,
	13: Keys.Enter,
	16: Keys.Shift,
	17: Keys.Ctrl,
	18: Keys.Alt,
	19: Keys.PauseBreak,
	20: Keys.CapsLock,
	27: Keys.Escape,
	32: Keys.Space,
	33: Keys.PageUp,
	34: Keys.PageDown,
	35: Keys.End,
	36: Keys.Home,
	37: Keys.Left,
	38: Keys.Up,
	39: Keys.Right,
	40: Keys.Down,
	45: Keys.Insert,
	46: Keys.Delete,
	91: Keys.Command,
	93: Keys.RightCommand,
	106: Keys.NumpadAsterisk,
	107: Keys.NumpadPlus,
	109: Keys.NumpadMinus,
	110: Keys.NumpadPeriod,
	111: Keys.NumpadForwardslash,
	144: Keys.NumLock,
	145: Keys.ScrollLock,
	182: Keys.MyComputer,
	183: Keys.MyCalculator,
	186: Keys.Semicolon,
	187: Keys.Equals,
	188: Keys.Comma,
	189: Keys.Dash,
	190: Keys.Period,
	191: Keys.Forwardslash,
	192: Keys.Quote,
	219: Keys.OpenBrace,
	220: Keys.Backslash,
	221: Keys.CloseBrace,
	222: Keys.Apostrophe,
	65: Keys.A,
	66: Keys.B,
	67: Keys.C,
	68: Keys.D,
	69: Keys.E,
	70: Keys.F,
	71: Keys.G,
	72: Keys.H,
	73: Keys.I,
	74: Keys.J,
	75: Keys.K,
	76: Keys.L,
	77: Keys.M,
	78: Keys.N,
	79: Keys.O,
	80: Keys.P,
	81: Keys.Q,
	82: Keys.R,
	83: Keys.S,
	84: Keys.T,
	85: Keys.U,
	86: Keys.V,
	87: Keys.W,
	88: Keys.X,
	89: Keys.Y,
	90: Keys.Z,
	112: Keys.F1,
	113: Keys.F2,
	114: Keys.F3,
	115: Keys.F4,
	116: Keys.F5,
	117: Keys.F6,
	118: Keys.F7,
	119: Keys.F8,
	120: Keys.F9,
	121: Keys.F10,
	122: Keys.F11,
	123: Keys.F12,
	96: Keys.Numpad0,
	97: Keys.Numpad1,
	98: Keys.Numpad2,
	99: Keys.Numpad3,
	100: Keys.Numpad4,
	101: Keys.Numpad5,
	102: Keys.Numpad6,
	103: Keys.Numpad7,
	104: Keys.Numpad8,
	105: Keys.Numpad9
};
