export enum PxRidgidBodyFlags {
	eKINEMATIC = 1 << 0,
	eUSE_KINEMATIC_TARGET_FOR_SCENE_QUERIES = 1 << 1,
	eENABLE_CCD = 1 << 2,
	eENABLE_CCD_FRICTION = 1 << 3,
	eENABLE_POSE_INTEGRATION_PREVIEW = 1 << 4,
	eENABLE_SPECULATIVE_CCD = 1 << 5,
	eENABLE_CCD_MAX_CONTACT_IMPULSE = 1 << 6,
	eRETAIN_ACCELERATIONS = 1 << 7
}
