export enum PxSceneFlag {
	eENABLE_ACTIVE_ACTORS = 1 << 0,
	eENABLE_CCD = 1 << 1,
	eDISABLE_CCD_RESWEEP = 1 << 2,
	eADAPTIVE_FORCE = 1 << 3,
	eENABLE_PCM = 1 << 6,
	eDISABLE_CONTACT_REPORT_BUFFER_RESIZE = 1 << 7,
	eDISABLE_CONTACT_CACHE = 1 << 8,
	eREQUIRE_RW_LOCK = 1 << 9,
	eENABLE_STABILIZATION = 1 << 10,
	eENABLE_AVERAGE_POINT = 1 << 11,
	eEXCLUDE_KINEMATICS_FROM_ACTIVE_ACTORS = 1 << 12,
	eENABLE_GPU_DYNAMICS = 1 << 13,
	eENABLE_ENHANCED_DETERMINISM = 1 << 14,
	eENABLE_FRICTION_EVERY_ITERATION = 1 << 15
}
